ALTER TABLE ingest_raw_file
  ADD COLUMN IF NOT EXISTS device_address TEXT,
  ADD COLUMN IF NOT EXISTS physical_group TEXT,
  ADD COLUMN IF NOT EXISTS schema_id TEXT;

ALTER TABLE utility_measurement_tall
  ADD COLUMN IF NOT EXISTS source_system TEXT,
  ADD COLUMN IF NOT EXISTS error_flag BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS low_alarm BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS high_alarm BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS device_address TEXT,
  ADD COLUMN IF NOT EXISTS physical_group TEXT;
